### ISSUE TITLE
Fix spdlog undefined reference error

### ISSUE THREAD

**Issue by MicheleMichetti** [MicheleMichetti/PokemonHiddenRed#7]
Compiling Map.cpp we encounter a problem if we compile including the spdlog library. Output:

`michele@michele-MS-7C56:~/Codes/Github_repositories/PokemonHiddenRed/PokemonHiddenRed$ sudo docker compose run play
mkdir: cannot create directory 'build': File exists
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /pokemon_game/build
[  6%] Building CXX object game/CMakeFiles/pokemon-lib.dir/src/Map.cpp.o
[ 12%] Linking CXX shared library libpokemon-lib.so
[ 56%] Built target pokemon-lib
[ 62%] Linking CXX executable pokemon
[ 68%] Built target pokemon
[ 75%] Linking CXX executable pokemon-tests
/usr/bin/ld: ../game/libpokemon-lib.so: undefined reference to `fmt::v8::detail::dragonbox::decimal_fp<float> fmt::v8::detail::dragonbox::to_decimal<float>(float)'
/usr/bin/ld: ../game/libpokemon-lib.so: undefined reference to `int fmt::v8::detail::snprintf_float<double>(double, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&)'
/usr/bin/ld: ../game/libpokemon-lib.so: undefined reference to `fmt::v8::detail::dragonbox::decimal_fp<double> fmt::v8::detail::dragonbox::to_decimal<double>(double)'
/usr/bin/ld: ../game/libpokemon-lib.so: undefined reference to `char fmt::v8::detail::decimal_point_impl<char>(fmt::v8::detail::locale_ref)'
/usr/bin/ld: ../game/libpokemon-lib.so: undefined reference to `int fmt::v8::detail::format_float<long double>(long double, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&)'
/usr/bin/ld: ../game/libpokemon-lib.so: undefined reference to `int fmt::v8::detail::format_float<double>(double, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&)'
/usr/bin/ld: ../game/libpokemon-lib.so: undefined reference to `fmt::v8::detail::throw_format_error(char const*)'
/usr/bin/ld: ../game/libpokemon-lib.so: undefined reference to `int fmt::v8::detail::snprintf_float<long double>(long double, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&)'
/usr/bin/ld: ../game/libpokemon-lib.so: undefined reference to `fmt::v8::detail::thousands_sep_result<char> fmt::v8::detail::thousands_sep_impl<char>(fmt::v8::detail::locale_ref)'
/usr/bin/ld: ../game/libpokemon-lib.so: undefined reference to `fmt::v8::detail::assert_fail(char const*, int, char const*)'
/usr/bin/ld: ../game/libpokemon-lib.so: undefined reference to `fmt::v8::detail::error_handler::on_error(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/pokemon-tests.dir/build.make:146: tests/pokemon-tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:170: tests/CMakeFiles/pokemon-tests.dir/all] Error 2
make: *** [Makefile:91: all] Error 2`

NOT A BLOCKING ISSUE BUT NEEDS TO BE SOLVED

**Comment by SparshLadani** [comment]
If you don't mind @MicheleMichetti can I give it try I'm a person who wants to contribute to open source and solve issues and bugs, though this will be my first time contributing to an open source project. Do let me know if this works for you.

**Comment by MicheleMichetti** [comment]
@SparshLadani Welcome and I would be glad if you could help me!
Before you start working on this, I would like to ask you to talk about the project and the way of working that we adopt, so we follow the same approach. Could you write me at michele.michetti91@gmail.com so we can schedule a meeting? I'm currently living in Rome (GMT+1) and I will be at work, I can answer in the evening.
